export const mockNewsData = [

 // Modified to Indian Stocks (Equity)

 {
 id: "3c148e8d-56b9-4476-b316-06d98883b9ad",
 name: "Bobby Axelrod",
 avatar: "https://randomuser.me/api/portraits/men/2.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Invest in TCS for strong IT growth.\nCompany nearing all-time highs signals potential upside.",
 symbol: "TCS",
 created_at: "2025-08-25T11:00:00Z", // 22 July 11am
 entry_price: 4200,
 exit_price: 4100,
 target_duration: "2 days",
 allocation: "10%",
 catalyst: "Upcoming IT sector earnings",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "RSI above 60, MACD bullish",
 confidence: "High",
 diversification: "Fits with equity exposure",
 liquidity: "High",
 expected_return: "8%",
 performance: "Last 3 tips: +7%, +5%, +9%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Momentum"
 },

 {
 id: 3,
 name: "Carol",
 avatar: "https://randomuser.me/api/portraits/women/3.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "Consider Reliance Industries for energy exposure.\nPrices volatile due to supply concerns.",
 symbol: "RELIANCE",
 created_at: "2025-08-22T11:00:00Z", // 22 July 11am
 entry_price: 3000,
 exit_price: 2900,
 target_duration: "3 days",
 allocation: "8%",
 catalyst: "OPEC meeting impact",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "RSI above 70, bearish divergence",
 confidence: "Moderate",
 diversification: "Complements energy exposure",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +4%, -2%, +6%",
 holding: "Sell",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Hedging"
 },

 {
 id: 4,
 name: "Dave",
 avatar: "https://randomuser.me/api/portraits/men/4.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Sun Pharma shows potential in pharma sector.\nFaces regulatory risks this quarter.",
 symbol: "SUNPHARMA",
 created_at: "2025-07-22T11:00:00Z", // 22 July 11am
 entry_price: 1500,
 exit_price: 1450,
 target_duration: "1 week",
 allocation: "7%",
 catalyst: "Drug approvals",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "MACD bearish crossover",
 confidence: "Moderate",
 diversification: "Balances healthcare exposure",
 liquidity: "Medium",
 expected_return: "5%",
 performance: "Last 3 tips: +3%, +4%, -1%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "65%",
 strategy: "Risk Management"
 },

 {
 id: 30,
 name: "Edward",
 avatar: "https://randomuser.me/api/portraits/men/30.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Leverage Infosys for IT gains.\nUpcoming events may shift prices.",
 symbol: "INFY",
 created_at: "2025-06-26T15:00:00Z",
 entry_price: 1800,
 exit_price: 1900,
 target_duration: "1 day",
 allocation: "15%",
 catalyst: "Sector growth",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "50DMA support",
 confidence: "Low",
 diversification: "Mitigates risk",
 liquidity: "High",
 expected_return: "7%",
 performance: "Last 3 tips: +9%, +7%, +6%",
 holding: "Hold",
 risk: "Low",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Momentum"
 },
 {
 id: 31,
 name: "Amy",
 avatar: "https://randomuser.me/api/portraits/women/31.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Consider Wipro to hedge IT risks.\nTraders expect swings soon.",
 symbol: "WIPRO",
 created_at: "2025-06-25T16:00:00Z",
 entry_price: 500,
 exit_price: 480,
 target_duration: "2 weeks",
 allocation: "10%",
 catalyst: "Regulatory news",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "MACD bullish crossover",
 confidence: "Moderate",
 diversification: "Diversifies exposure",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +4%, +6%, +2%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Hedging"
 },
 {
 id: 32,
 name: "Brandon",
 avatar: "https://randomuser.me/api/portraits/men/32.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "Consider ONGC for energy exposure.\nTraders expect swings soon.",
 symbol: "ONGC",
 created_at: "2025-06-24T17:00:00Z",
 entry_price: 250,
 exit_price: 240,
 target_duration: "1 week",
 allocation: "12%",
 catalyst: "Monetary policy",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "RSI below 37",
 confidence: "Moderate",
 diversification: "Reduces portfolio volatility",
 liquidity: "Medium",
 expected_return: "5%",
 performance: "Last 3 tips: +3%, +6%, +0%",
 holding: "Sell",
 risk: "High",
 conviction: "Medium",
 win_rate: "60%",
 strategy: "Risk Management"
 },
 {
 id: 33,
 name: "Deborah",
 avatar: "https://randomuser.me/api/portraits/women/33.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "BPCL shows potential in energy.\nMarket volatility suggests caution.",
 symbol: "BPCL",
 created_at: "2025-06-23T18:00:00Z",
 entry_price: 600,
 exit_price: 580,
 target_duration: "6 months",
 allocation: "15%",
 catalyst: "New technology development",
 valuation: "Fair",
 sentiment: "Bearish",
 technical: "RSI below 29",
 confidence: "High",
 diversification: "Diversifies exposure",
 liquidity: "Very High",
 expected_return: "4%",
 performance: "Last 3 tips: +10%, +4%, -4%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Long-Term Growth"
 },
 {
 id: 34,
 name: "Stephen",
 avatar: "https://randomuser.me/api/portraits/men/34.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Cipla offers growth in pharma.\nTraders expect swings soon.",
 symbol: "CIPLA",
 created_at: "2025-06-22T19:00:00Z",
 entry_price: 1200,
 exit_price: 1250,
 target_duration: "2 weeks",
 allocation: "9%",
 catalyst: "Sector growth",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "MACD turning up",
 confidence: "High",
 diversification: "Reduces volatility",
 liquidity: "Very High",
 expected_return: "9%",
 performance: "Last 3 tips: +10%, +7%, +1%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Momentum"
 },
 {
 id: 35,
 name: "Brianna",
 avatar: "https://randomuser.me/api/portraits/women/35.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Dr Reddy's Labs for pharma stability.\nMarket volatility suggests caution.",
 symbol: "DRREDDY",
 created_at: "2025-06-21T20:00:00Z",
 entry_price: 5500,
 exit_price: 5400,
 target_duration: "3 days",
 allocation: "9%",
 catalyst: "Sector growth",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Bollinger Bands widening",
 confidence: "Low",
 diversification: "Complements fixed income exposure",
 liquidity: "Very High",
 expected_return: "9%",
 performance: "Last 3 tips: +0%, +9%, +8%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "74%",
 strategy: "Speculative"
 },
 {
 id: 36,
 name: "Charles",
 avatar: "https://randomuser.me/api/portraits/men/36.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "HDFC Bank for banking stability.\nMarket volatility suggests caution.",
 symbol: "HDFCBANK",
 created_at: "2025-06-20T21:00:00Z",
 entry_price: 1600,
 exit_price: 1550,
 target_duration: "1 month",
 allocation: "10%",
 catalyst: "Economic data release",
 valuation: "Fair",
 sentiment: "Bearish",
 technical: "50DMA resistance",
 confidence: "Moderate",
 diversification: "Fits with overall strategy",
 liquidity: "High",
 expected_return: "7%",
 performance: "Last 3 tips: +8%, -2%, +5%",
 holding: "Sell",
 risk: "High",
 conviction: "Medium",
 win_rate: "68%",
 strategy: "Risk Management"
 },
 {
 id: 37,
 name: "Donna",
 avatar: "https://randomuser.me/api/portraits/women/37.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "ICICI Bank for financial growth.\nMarket volatility suggests caution.",
 symbol: "ICICIBANK",
 created_at: "2025-06-19T22:00:00Z",
 entry_price: 1100,
 exit_price: 1050,
 target_duration: "3 months",
 allocation: "11%",
 catalyst: "RBI policy",
 valuation: "Overvalued",
 sentiment: "Neutral",
 technical: "RSI at 42",
 confidence: "High",
 diversification: "Reduces portfolio volatility",
 liquidity: "Medium",
 expected_return: "5%",
 performance: "Last 3 tips: +7%, +2%, +6%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },
 {
 id: 38,
 name: "Ellen",
 avatar: "https://randomuser.me/api/portraits/women/38.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Tech Mahindra for IT exposure.\nMarket volatility suggests caution.",
 symbol: "TECHM",
 created_at: "2025-06-18T23:00:00Z",
 entry_price: 1400,
 exit_price: 1450,
 target_duration: "6 months",
 allocation: "13%",
 catalyst: "Interest rate decision",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "Moving average bullish crossover",
 confidence: "Moderate",
 diversification: "Diversifies exposure",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +4%, +5%, +7%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "78%",
 strategy: "Long-Term Growth"
 },
 {
 id: 39,
 name: "Patricia",
 avatar: "https://randomuser.me/api/portraits/women/39.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "IOC for energy portfolio protection.\nMarket volatility suggests caution.",
 symbol: "IOC",
 created_at: "2025-06-17T00:00:00Z",
 entry_price: 170,
 exit_price: 160,
 target_duration: "2 days",
 allocation: "20%",
 catalyst: "Economic data release",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "50DMA support",
 confidence: "Moderate",
 diversification: "Complements equity exposure",
 liquidity: "Very High",
 expected_return: "9%",
 performance: "Last 3 tips: -5%, +1%, -5%",
 holding: "Sell",
 risk: "Medium",
 conviction: "Weak",
 win_rate: "80%",
 strategy: "Passive Indexing"
 },

 // Modified Indexes to Indian Stocks (Equity)

 {
 id: 5,
 name: "Eve",
 avatar: "https://randomuser.me/api/portraits/women/5.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "TCS for broad IT exposure.\nTech earnings may drive performance.",
 symbol: "TCS",
 created_at: "2025-07-21T14:00:00Z",
 entry_price: 4200,
 exit_price: 4100,
 target_duration: "1 week",
 allocation: "15%",
 catalyst: "Tech earnings season",
 valuation: "Undervalued",
 sentiment: "Neutral",
 technical: "50DMA support",
 confidence: "Moderate",
 diversification: "Balances sector risk",
 liquidity: "Very High",
 expected_return: "5%",
 performance: "Stock up 12% YTD",
 holding: "Hold",
 risk: "Low",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Passive Indexing"
 },

 {
 id: 6,
 name: "Frank",
 avatar: "https://randomuser.me/api/portraits/men/6.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "SBI for banking trends.\nBanking sector shows strong Q2 earnings.",
 symbol: "SBIN",
 created_at: "2025-07-20T15:00:00Z",
 entry_price: 800,
 exit_price: 780,
 target_duration: "1 month",
 allocation: "12%",
 catalyst: "RBI rate decision",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "RSI above 55, bullish trend",
 confidence: "High",
 diversification: "Complements equity portfolio",
 liquidity: "High",
 expected_return: "7%",
 performance: "Stock up 10% YTD",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Trend Following"
 },

 {
 id: 7,
 name: "Grace",
 avatar: "https://randomuser.me/api/portraits/women/7.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "Reliance shows bullish momentum.\nOil price trends support growth.",
 symbol: "RELIANCE",
 created_at: "2025-07-19T16:00:00Z",
 entry_price: 3000,
 exit_price: 2900,
 target_duration: "2 weeks",
 allocation: "10%",
 catalyst: "Geopolitical tensions",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "Moderate",
 diversification: "Balances commodity exposure",
 liquidity: "Medium",
 expected_return: "6%",
 performance: "Stock up 8% YTD",
 holding: "Buy",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Momentum"
 },

 {
 id: 8,
 name: "Henry",
 avatar: "https://randomuser.me/api/portraits/men/8.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Sun Pharma outperforms in Q2.\nStrong R&D pipelines drive growth.",
 symbol: "SUNPHARMA",
 created_at: "2025-08-23T17:00:00Z",
 entry_price: 1500,
 exit_price: 1450,
 target_duration: "3 weeks",
 allocation: "9%",
 catalyst: "New drug approvals",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "50DMA resistance",
 confidence: "Moderate",
 diversification: "Reduces sector risk",
 liquidity: "High",
 expected_return: "5%",
 performance: "Stock up 9% YTD",
 holding: "Hold",
 risk: "Low",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Value Investing"
 },

 {
 id: 40,
 name: "Evan",
 avatar: "https://randomuser.me/api/portraits/men/40.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Infosys to gauge IT momentum.\nSector performances will play a role.",
 symbol: "INFY",
 created_at: "2025-06-16T01:00:00Z",
 entry_price: 1800,
 exit_price: 1700,
 target_duration: "3 months",
 allocation: "12%",
 catalyst: "Sector growth",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "High",
 diversification: "Balances sector risk",
 liquidity: "High",
 expected_return: "10%",
 performance: "Stock up 14% YTD",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "82%",
 strategy: "Value Investing"
 },
 {
 id: 41,
 name: "Fiona",
 avatar: "https://randomuser.me/api/portraits/women/41.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "HCL Tech for broad IT exposure.\nEconomic data or earnings may shift it.",
 symbol: "HCLTECH",
 created_at: "2025-06-15T02:00:00Z",
 entry_price: 1400,
 exit_price: 1350,
 target_duration: "6 months",
 allocation: "14%",
 catalyst: "Economic data release",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "50DMA support",
 confidence: "Moderate",
 diversification: "Diversifies exposure",
 liquidity: "Very High",
 expected_return: "6%",
 performance: "Stock up 15% YTD",
 holding: "Hold",
 risk: "Low",
 conviction: "Medium",
 win_rate: "76%",
 strategy: "Long-Term Growth"
 },
 {
 id: 42,
 name: "George",
 avatar: "https://randomuser.me/api/portraits/men/42.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "ONGC for broad energy exposure.\nTrade data might influence movement.",
 symbol: "ONGC",
 created_at: "2025-06-14T03:00:00Z",
 entry_price: 250,
 exit_price: 240,
 target_duration: "1 month",
 allocation: "13%",
 catalyst: "Geopolitical event",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "RSI above 65",
 confidence: "High",
 diversification: "Complements portfolio",
 liquidity: "High",
 expected_return: "5%",
 performance: "Stock up 11% YTD",
 holding: "Sell",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Trend Following"
 },
 {
 id: 43,
 name: "Hannah",
 avatar: "https://randomuser.me/api/portraits/women/43.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "BPCL as energy trends evolve.\nSector performances will play a role.",
 symbol: "BPCL",
 created_at: "2025-06-13T04:00:00Z",
 entry_price: 600,
 exit_price: 580,
 target_duration: "2 weeks",
 allocation: "12%",
 catalyst: "Market rally",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "Moderate",
 diversification: "Balances sector risk",
 liquidity: "High",
 expected_return: "7%",
 performance: "Stock up 13% YTD",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Trend Following"
 },
 {
 id: 44,
 name: "Ian",
 avatar: "https://randomuser.me/api/portraits/men/44.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Cipla as healthcare improves.\nRBI decisions could matter.",
 symbol: "CIPLA",
 created_at: "2025-06-12T05:00:00Z",
 entry_price: 1200,
 exit_price: 1250,
 target_duration: "3 weeks",
 allocation: "11%",
 catalyst: "Regulatory news",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "Moving average bullish crossover",
 confidence: "High",
 diversification: "Diversifies exposure",
 liquidity: "High",
 expected_return: "8%",
 performance: "Stock up 12% YTD",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "88%",
 strategy: "Value Investing"
 },
 {
 id: 45,
 name: "Jane",
 avatar: "https://randomuser.me/api/portraits/women/45.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Divis Labs to gauge pharma momentum.\nSector performances will play a role.",
 symbol: "DIVISLAB",
 created_at: "2025-06-11T06:00:00Z",
 entry_price: 4500,
 exit_price: 4400,
 target_duration: "1 week",
 allocation: "10%",
 catalyst: "Tech earnings",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "RSI at 52",
 confidence: "Moderate",
 diversification: "Balances sector risk",
 liquidity: "Very High",
 expected_return: "4%",
 performance: "Stock up 10% YTD",
 holding: "Hold",
 risk: "Low",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Passive Indexing"
 },
 {
 id: 46,
 name: "Kyle",
 avatar: "https://randomuser.me/api/portraits/men/46.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "Axis Bank for broad banking exposure.\nRBI actions matter.",
 symbol: "AXISBANK",
 created_at: "2025-06-10T07:00:00Z",
 entry_price: 1200,
 exit_price: 1250,
 target_duration: "2 weeks",
 allocation: "12%",
 catalyst: "Interest rate decision",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "Bollinger Bands widening",
 confidence: "High",
 diversification: "Complements portfolio",
 liquidity: "High",
 expected_return: "7%",
 performance: "Stock up 16% YTD",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Trend Following"
 },
 {
 id: 47,
 name: "Lily",
 avatar: "https://randomuser.me/api/portraits/women/47.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "Kotak Bank to gauge banking momentum.\nEarnings reports could shift it.",
 symbol: "KOTAKBANK",
 created_at: "2025-06-09T08:00:00Z",
 entry_price: 1800,
 exit_price: 1750,
 target_duration: "3 weeks",
 allocation: "9%",
 catalyst: "Earnings reports",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "RSI above 64",
 confidence: "Moderate",
 diversification: "Diversifies exposure",
 liquidity: "High",
 expected_return: "5%",
 performance: "Stock up 14% YTD",
 holding: "Sell",
 risk: "High",
 conviction: "Medium",
 win_rate: "72%",
 strategy: "Speculative"
 },
 {
 id: 48,
 name: "Benjamin",
 avatar: "https://randomuser.me/api/portraits/men/48.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Wipro to gauge IT momentum.\nEconomic data or earnings may shift it.",
 symbol: "WIPRO",
 created_at: "2025-06-08T09:00:00Z",
 entry_price: 500,
 exit_price: 550,
 target_duration: "2 days",
 allocation: "6%",
 catalyst: "Commodity price changes",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "Bollinger Bands widening",
 confidence: "Low",
 diversification: "Complements portfolio",
 liquidity: "High",
 expected_return: "3%",
 performance: "Stock up 12% YTD",
 holding: "Buy",
 risk: "Low",
 conviction: "Weak",
 win_rate: "93%",
 strategy: "Trend Following"
 },

 // Modified Bonds to Indian Stocks (Equity)

 {
 id: 9,
 name: "Ivy",
 avatar: "https://randomuser.me/api/portraits/women/9.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "SBI for banking stability.\nReturns remain attractive in high-rate environment.",
 symbol: "SBIN",
 created_at: "2025-07-17T18:00:00Z",
 entry_price: 800,
 exit_price: 780,
 target_duration: "6 months",
 allocation: "20%",
 catalyst: "RBI policy",
 valuation: "Undervalued",
 sentiment: "Neutral",
 technical: "Yield curve steepening",
 confidence: "High",
 diversification: "Reduces portfolio volatility",
 liquidity: "Very High",
 expected_return: "3%",
 performance: "Last 3 tips: +2%, +1%, +3%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Income"
 },

 {
 id: 10,
 name: "Jack",
 avatar: "https://randomuser.me/api/portraits/men/10.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Infosys offers higher returns.\nSector growth supports performance.",
 symbol: "INFY",
 created_at: "2025-07-16T19:00:00Z",
 entry_price: 1800,
 exit_price: 1750,
 target_duration: "3 months",
 allocation: "15%",
 catalyst: "Tech earnings growth",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "Stable yield trends",
 confidence: "Moderate",
 diversification: "Balances tech equity risk",
 liquidity: "Medium",
 expected_return: "4%",
 performance: "Last 3 tips: +3%, +2%, +4%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Income"
 },

 {
 id: 11,
 name: "Kate",
 avatar: "https://randomuser.me/api/portraits/women/11.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "Reliance is less volatile.\nStable cash flows ensure reliability.",
 symbol: "RELIANCE",
 created_at: "2025-07-15T20:00:00Z",
 entry_price: 3000,
 exit_price: 2950,
 target_duration: "1 year",
 allocation: "12%",
 catalyst: "Oil price stabilization",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Consistent yield support",
 confidence: "High",
 diversification: "Complements energy stocks",
 liquidity: "Medium",
 expected_return: "7%",
 performance: "Last 3 tips: +4%, +3%, +5%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },

 {
 id: 12,
 name: "Leo",
 avatar: "https://randomuser.me/api/portraits/men/12.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Cipla is a safe haven.\nStrong fundamentals reduce risk.",
 symbol: "CIPLA",
 created_at: "2025-07-14T21:00:00Z",
 entry_price: 1200,
 exit_price: 1150,
 target_duration: "6 months",
 allocation: "10%",
 catalyst: "Healthcare reforms",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "Yield curve flattening",
 confidence: "High",
 diversification: "Reduces sector volatility",
 liquidity: "High",
 expected_return: "3%",
 performance: "Last 3 tips: +2%, +3%, +2%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "90%",
 strategy: "Income"
 },

 {
 id: 49,
 name: "Ivan",
 avatar: "https://randomuser.me/api/portraits/men/49.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "TCS for stability.\nReturns remain attractive in current climate.",
 symbol: "TCS",
 created_at: "2025-06-17T10:00:00Z",
 entry_price: 4200,
 exit_price: 4100,
 target_duration: "1 year",
 allocation: "12%",
 catalyst: "Inflation data",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Yield curve steepening",
 confidence: "Moderate",
 diversification: "Reduces portfolio volatility",
 liquidity: "High",
 expected_return: "4%",
 performance: "Last 3 tips: +2%, +1%, +3%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Income"
 },
 {
 id: 50,
 name: "Jasmine",
 avatar: "https://randomuser.me/api/portraits/women/50.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Wipro for stability.\nReturns remain attractive in current climate.",
 symbol: "WIPRO",
 created_at: "2025-06-16T11:00:00Z",
 entry_price: 500,
 exit_price: 480,
 target_duration: "2 months",
 allocation: "10%",
 catalyst: "RBI policy",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Stable yield trends",
 confidence: "High",
 diversification: "Reduces portfolio volatility",
 liquidity: "High",
 expected_return: "3%",
 performance: "Last 3 tips: +2%, +0%, +1%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Income"
 },
 {
 id: 51,
 name: "Kevin",
 avatar: "https://randomuser.me/api/portraits/men/51.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "ONGC for income.\nStable cash flows support returns.",
 symbol: "ONGC",
 created_at: "2025-06-15T12:00:00Z",
 entry_price: 250,
 exit_price: 240,
 target_duration: "6 months",
 allocation: "8%",
 catalyst: "Oil production news",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Consistent yield support",
 confidence: "Moderate",
 diversification: "Complements energy stocks",
 liquidity: "Medium",
 expected_return: "5%",
 performance: "Last 3 tips: +3%, +2%, +4%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Income"
 },
 {
 id: 52,
 name: "Laura",
 avatar: "https://randomuser.me/api/portraits/women/52.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "BPCL offers stability.\nStable cash flows support returns.",
 symbol: "BPCL",
 created_at: "2025-06-14T13:00:00Z",
 entry_price: 600,
 exit_price: 580,
 target_duration: "3 months",
 allocation: "9%",
 catalyst: "Oil price movement",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Yield curve flattening",
 confidence: "Moderate",
 diversification: "Complements energy stocks",
 liquidity: "Medium",
 expected_return: "4%",
 performance: "Last 3 tips: +2%, +1%, +3%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },
 {
 id: 53,
 name: "Michael",
 avatar: "https://randomuser.me/api/portraits/men/53.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Sun Pharma for higher income.\nCompanies generating steady cash flow.",
 symbol: "SUNPHARMA",
 created_at: "2025-06-13T14:00:00Z",
 entry_price: 1500,
 exit_price: 1450,
 target_duration: "1 year",
 allocation: "10%",
 catalyst: "Corporate earnings",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "Stable yield trends",
 confidence: "High",
 diversification: "Balances portfolio risk",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +4%, +3%, +5%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Income"
 },
 {
 id: 54,
 name: "Natalie",
 avatar: "https://randomuser.me/api/portraits/women/54.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Dr Reddy's has solid returns.\nStable cash flows support returns.",
 symbol: "DRREDDY",
 created_at: "2025-06-12T15:00:00Z",
 entry_price: 5500,
 exit_price: 5400,
 target_duration: "6 months",
 allocation: "11%",
 catalyst: "Regulatory changes",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Consistent yield support",
 confidence: "High",
 diversification: "Balances portfolio risk",
 liquidity: "Medium",
 expected_return: "5%",
 performance: "Last 3 tips: +3%, +2%, +4%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "82%",
 strategy: "Income"
 },
 {
 id: 55,
 name: "Oliver",
 avatar: "https://randomuser.me/api/portraits/men/55.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "HDFC Bank offers broad exposure.\nBank stocks are stable.",
 symbol: "HDFCBANK",
 created_at: "2025-06-11T16:00:00Z",
 entry_price: 1600,
 exit_price: 1550,
 target_duration: "6 months",
 allocation: "12%",
 catalyst: "RBI meeting",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "Yield curve steepening",
 confidence: "High",
 diversification: "Core portfolio holding",
 liquidity: "High",
 expected_return: "3%",
 performance: "Last 3 tips: +2%, +1%, +2%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Income"
 },
 {
 id: 56,
 name: "Paul",
 avatar: "https://randomuser.me/api/portraits/men/56.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "ICICI Bank for banking exposure.\nSafe returns in uncertain times.",
 symbol: "ICICIBANK",
 created_at: "2025-06-10T17:00:00Z",
 entry_price: 1100,
 exit_price: 1050,
 target_duration: "1 year",
 allocation: "15%",
 catalyst: "Economic reports",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Stable yield trends",
 confidence: "High",
 diversification: "Core portfolio holding",
 liquidity: "Very High",
 expected_return: "3%",
 performance: "Last 3 tips: +1%, +0%, +1%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "87%",
 strategy: "Income"
 },

 // Modified Commodities to Indian Stocks (Equity)

 {
 id: 13,
 name: "Mona",
 avatar: "https://randomuser.me/api/portraits/women/13.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "Reliance is a hedge against inflation.\nRising rates increase appeal.",
 symbol: "RELIANCE",
 created_at: "2025-07-13T22:00:00Z",
 entry_price: 3000,
 exit_price: 2900,
 target_duration: "1 month",
 allocation: "8%",
 catalyst: "Inflation data release",
 valuation: "Overvalued",
 sentiment: "Neutral",
 technical: "RSI at 50, neutral trend",
 confidence: "Moderate",
 diversification: "Balances equity risk",
 liquidity: "High",
 expected_return: "5%",
 performance: "Last 3 tips: +6%, +4%, +7%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Safe Haven"
 },

 {
 id: 14,
 name: "Nate",
 avatar: "https://randomuser.me/api/portraits/men/14.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "Axis Bank demand rises.\nIndustrial use drives growth.",
 symbol: "AXISBANK",
 created_at: "2025-07-12T23:00:00Z",
 entry_price: 1200,
 exit_price: 1150,
 target_duration: "2 weeks",
 allocation: "7%",
 catalyst: "Tech production increase",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "MACD bullish signal",
 confidence: "Moderate",
 diversification: "Complements tech assets",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +5%, +3%, +6%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Momentum"
 },

 {
 id: 15,
 name: "Olivia",
 avatar: "https://randomuser.me/api/portraits/women/15.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "HCL Tech prices may rise.\nData center expansion drives demand.",
 symbol: "HCLTECH",
 created_at: "2025-07-11T00:00:00Z",
 entry_price: 1400,
 exit_price: 1350,
 target_duration: "1 month",
 allocation: "6%",
 catalyst: "Tech infrastructure growth",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "RSI below 40, oversold",
 confidence: "High",
 diversification: "Enhances tech exposure",
 liquidity: "Medium",
 expected_return: "8%",
 performance: "Last 3 tips: +7%, +5%, +8%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Growth"
 },

 {
 id: 16,
 name: "Paul",
 avatar: "https://randomuser.me/api/portraits/men/16.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Divis Labs used in medical sector.\nHealthcare innovation boosts demand.",
 symbol: "DIVISLAB",
 created_at: "2025-07-10T01:00:00Z",
 entry_price: 4500,
 exit_price: 4400,
 target_duration: "3 weeks",
 allocation: "5%",
 catalyst: "Medical tech advancements",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "50DMA support",
 confidence: "Moderate",
 diversification: "Balances healthcare portfolio",
 liquidity: "Medium",
 expected_return: "6%",
 performance: "Last 3 tips: +4%, +5%, +3%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Value"
 },
 {
 id: 58,
 name: "Quentin",
 avatar: "https://randomuser.me/api/portraits/men/58.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Tech Mahindra demand is rising.\nSupply chain issues may impact prices.",
 symbol: "TECHM",
 created_at: "2025-06-09T10:00:00Z",
 entry_price: 1400,
 exit_price: 1350,
 target_duration: "1 month",
 allocation: "7%",
 catalyst: "Supply disruptions",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "RSI at 55",
 confidence: "Moderate",
 diversification: "Diversifies portfolio",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +3%, +2%, +1%",
 holding: "Hold",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Growth"
 },
 {
 id: 59,
 name: "Rebecca",
 avatar: "https://randomuser.me/api/portraits/women/59.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Monitor Infosys amid IT demand.\nIndustrial consumption may keep prices high.",
 symbol: "INFY",
 created_at: "2025-06-08T11:00:00Z",
 entry_price: 1800,
 exit_price: 1700,
 target_duration: "2 weeks",
 allocation: "5%",
 catalyst: "Industrial demand",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "RSI above 60",
 confidence: "Moderate",
 diversification: "Balances tech exposure",
 liquidity: "High",
 expected_return: "4%",
 performance: "Last 3 tips: +2%, +1%, -1%",
 holding: "Sell",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "65%",
 strategy: "Momentum"
 },
 {
 id: 60,
 name: "Sean",
 avatar: "https://randomuser.me/api/portraits/men/60.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "Reliance shows bullish trend.\nImproving global demand drives prices.",
 symbol: "RELIANCE",
 created_at: "2025-06-07T12:00:00Z",
 entry_price: 3000,
 exit_price: 3100,
 target_duration: "2 weeks",
 allocation: "6%",
 catalyst: "Industrial demand",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "RSI above 55",
 confidence: "High",
 diversification: "Balances tech exposure",
 liquidity: "High",
 expected_return: "8%",
 performance: "Last 3 tips: +7%, +6%, +8%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Momentum"
 },
 {
 id: 61,
 name: "Tracy",
 avatar: "https://randomuser.me/api/portraits/women/61.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "IOC prices may rise.\nDemand from sector increases.",
 symbol: "IOC",
 created_at: "2025-06-06T13:00:00Z",
 entry_price: 170,
 exit_price: 180,
 target_duration: "1 month",
 allocation: "8%",
 catalyst: "Demand growth",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "MACD bullish signal",
 confidence: "Moderate",
 diversification: "Diversifies portfolio",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +6%, +4%, +5%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Trend Following"
 },
 {
 id: 62,
 name: "Uma",
 avatar: "https://randomuser.me/api/portraits/women/62.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Sun Pharma remains steady.\nSafe-haven appeal in volatile markets.",
 symbol: "SUNPHARMA",
 created_at: "2025-06-05T14:00:00Z",
 entry_price: 1500,
 exit_price: 1450,
 target_duration: "1 month",
 allocation: "7%",
 catalyst: "Inflation data",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Bollinger Bands narrowing",
 confidence: "Moderate",
 diversification: "Safe-haven asset",
 liquidity: "High",
 expected_return: "5%",
 performance: "Last 3 tips: +2%, +1%, +3%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "78%",
 strategy: "Safe Haven"
 },
 {
 id: 63,
 name: "Victor",
 avatar: "https://randomuser.me/api/portraits/men/63.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Cipla demand holds steady.\nIndustrial use maintains support.",
 symbol: "CIPLA",
 created_at: "2025-06-04T15:00:00Z",
 entry_price: 1200,
 exit_price: 1150,
 target_duration: "2 weeks",
 allocation: "5%",
 catalyst: "Industrial demand",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "50DMA support",
 confidence: "Moderate",
 diversification: "Diversifies portfolio",
 liquidity: "High",
 expected_return: "4%",
 performance: "Last 3 tips: +3%, +2%, +4%",
 holding: "Hold",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "72%",
 strategy: "Value"
 },
 {
 id: 64,
 name: "Wendy",
 avatar: "https://randomuser.me/api/portraits/women/64.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "SBI prices stabilize.\nGlobal supply supports current prices.",
 symbol: "SBIN",
 created_at: "2025-06-03T16:00:00Z",
 entry_price: 800,
 exit_price: 780,
 target_duration: "3 months",
 allocation: "6%",
 catalyst: "Market reports",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Moving average resistance",
 confidence: "High",
 diversification: "Diversifies portfolio",
 liquidity: "High",
 expected_return: "5%",
 performance: "Last 3 tips: +4%, +3%, +5%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },
 {
 id: 65,
 name: "Xander",
 avatar: "https://randomuser.me/api/portraits/men/65.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "HDFC Bank remains in demand.\nMarket trends drive prices up.",
 symbol: "HDFCBANK",
 created_at: "2025-06-02T17:00:00Z",
 entry_price: 1600,
 exit_price: 1650,
 target_duration: "1 month",
 allocation: "7%",
 catalyst: "Market forecasts",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "RSI above 60",
 confidence: "High",
 diversification: "Diversifies energy exposure",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +5%, +4%, +6%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Growth"
 },

 // Modified Forex to Indian Stocks (Equity)

 {
 id: 17,
 name: "Quinn",
 avatar: "https://randomuser.me/api/portraits/women/17.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "SBI expected to remain stable.\nRBI policies support balance.",
 symbol: "SBIN",
 created_at: "2025-07-09T02:00:00Z",
 entry_price: 800,
 exit_price: 780,
 target_duration: "2 weeks",
 allocation: "10%",
 catalyst: "RBI monetary policy",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Bollinger Bands narrowing",
 confidence: "High",
 diversification: "Reduces currency risk",
 liquidity: "Very High",
 expected_return: "3%",
 performance: "Last 3 tips: +2%, +1%, +3%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Stability"
 },

 {
 id: 18,
 name: "Ray",
 avatar: "https://randomuser.me/api/portraits/men/18.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Infosys may see volatility soon.\nTech earnings could impact.",
 symbol: "INFY",
 created_at: "2025-07-08T03:00:00Z",
 entry_price: 1800,
 exit_price: 1750,
 target_duration: "1 week",
 allocation: "8%",
 catalyst: "Tech earnings reports",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "RSI above 65",
 confidence: "Moderate",
 diversification: "Balances tech exposure",
 liquidity: "Very High",
 expected_return: "4%",
 performance: "Last 3 tips: +3%, -1%, +4%",
 holding: "Sell",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Speculative"
 },

 {
 id: 19,
 name: "Sara",
 avatar: "https://randomuser.me/api/portraits/women/19.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "Reliance correlates with oil prices.\nEnergy market trends drive.",
 symbol: "RELIANCE",
 created_at: "2025-07-07T04:00:00Z",
 entry_price: 3000,
 exit_price: 2900,
 target_duration: "2 weeks",
 allocation: "7%",
 catalyst: "Oil price fluctuations",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "MACD bullish signal",
 confidence: "Moderate",
 diversification: "Complements energy assets",
 liquidity: "High",
 expected_return: "5%",
 performance: "Last 3 tips: +4%, +2%, +5%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Trend Following"
 },

 {
 id: 20,
 name: "Tom",
 avatar: "https://randomuser.me/api/portraits/men/20.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Sun Pharma may strengthen on reforms.\nHealthcare policies boost.",
 symbol: "SUNPHARMA",
 created_at: "2025-07-06T05:00:00Z",
 entry_price: 1500,
 exit_price: 1450,
 target_duration: "1 month",
 allocation: "6%",
 catalyst: "Healthcare reforms",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "RSI below 40, oversold",
 confidence: "High",
 diversification: "Reduces forex volatility",
 liquidity: "Very High",
 expected_return: "6%",
 performance: "Last 3 tips: +5%, +3%, +6%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Value"
 },
 {
 id: 66,
 name: "Uma",
 avatar: "https://randomuser.me/api/portraits/women/66.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "TCS is steady.\nStable trends expected ahead.",
 symbol: "TCS",
 created_at: "2025-06-06T18:00:00Z",
 entry_price: 4200,
 exit_price: 4100,
 target_duration: "2 weeks",
 allocation: "10%",
 catalyst: "RBI meeting",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "MACD neutral",
 confidence: "Moderate",
 diversification: "Reduces currency risk",
 liquidity: "Very High",
 expected_return: "2%",
 performance: "Last 3 tips: +1%, +0%, +1%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Stability"
 },
 {
 id: 67,
 name: "Victor",
 avatar: "https://randomuser.me/api/portraits/men/67.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "Monitor ONGC with commodity trends.\nRecent demand influences rate.",
 symbol: "ONGC",
 created_at: "2025-06-05T19:00:00Z",
 entry_price: 250,
 exit_price: 260,
 target_duration: "3 weeks",
 allocation: "8%",
 catalyst: "Commodity data",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "High",
 diversification: "Reduces forex volatility",
 liquidity: "Very High",
 expected_return: "5%",
 performance: "Last 3 tips: +4%, +3%, +6%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Trend Following"
 },
 {
 id: 68,
 name: "Wendy",
 avatar: "https://randomuser.me/api/portraits/women/68.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Cipla influenced by policy.\nRBI decisions matter.",
 symbol: "CIPLA",
 created_at: "2025-06-04T20:00:00Z",
 entry_price: 1200,
 exit_price: 1150,
 target_duration: "2 weeks",
 allocation: "7%",
 catalyst: "Interest rate",
 valuation: "Overvalued",
 sentiment: "Bearish",
 technical: "RSI above 70",
 confidence: "Moderate",
 diversification: "Balances currency risk",
 liquidity: "Very High",
 expected_return: "4%",
 performance: "Last 3 tips: +3%, +1%, +2%",
 holding: "Sell",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Speculative"
 },
 {
 id: 69,
 name: "Xander",
 avatar: "https://randomuser.me/api/portraits/men/69.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "HDFC Bank reflects market tensions.\nGlobal news drives movement.",
 symbol: "HDFCBANK",
 created_at: "2025-06-03T21:00:00Z",
 entry_price: 1600,
 exit_price: 1550,
 target_duration: "1 month",
 allocation: "9%",
 catalyst: "Trade news",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "MACD neutral",
 confidence: "Moderate",
 diversification: "Balances currency risk",
 liquidity: "Very High",
 expected_return: "3%",
 performance: "Last 3 tips: +2%, +0%, +1%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "82%",
 strategy: "Stability"
 },
 {
 id: 70,
 name: "Yara",
 avatar: "https://randomuser.me/api/portraits/women/70.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "ICICI Bank remains calm.\nRBI policy at play.",
 symbol: "ICICIBANK",
 created_at: "2025-06-02T22:00:00Z",
 entry_price: 1100,
 exit_price: 1050,
 target_duration: "1 week",
 allocation: "6%",
 catalyst: "RBI meeting",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "RSI at 49",
 confidence: "High",
 diversification: "Balances currency risk",
 liquidity: "Very High",
 expected_return: "3%",
 performance: "Last 3 tips: +2%, +1%, +1%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "84%",
 strategy: "Stability"
 },

 // Modified Equity to Indian Stocks (Equity)

 {
 id: 21,
 name: "Uma",
 avatar: "https://randomuser.me/api/portraits/women/21.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "TCS stock remains a strong buy.\nInnovation drives long-term growth.",
 symbol: "TCS",
 created_at: "2025-07-05T06:00:00Z",
 entry_price: 4200,
 exit_price: 4100,
 target_duration: "3 months",
 allocation: "15%",
 catalyst: "Product launch",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "RSI at 55, uptrend",
 confidence: "High",
 diversification: "Core tech holding",
 liquidity: "Very High",
 expected_return: "10%",
 performance: "Last 3 tips: +8%, +6%, +9%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Growth"
 },

 {
 id: 22,
 name: "Victor",
 avatar: "https://randomuser.me/api/portraits/men/22.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "HDFC Bank shows potential.\nStrong Q2 earnings support growth.",
 symbol: "HDFCBANK",
 created_at: "2025-07-04T07:00:00Z",
 entry_price: 1600,
 exit_price: 1550,
 target_duration: "2 months",
 allocation: "12%",
 catalyst: "Earnings report",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "Moderate",
 diversification: "Balances financial exposure",
 liquidity: "High",
 expected_return: "8%",
 performance: "Last 3 tips: +6%, +4%, +7%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Value"
 },

 {
 id: 23,
 name: "Wendy",
 avatar: "https://randomuser.me/api/portraits/women/23.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "Reliance is a solid dividend stock.\nEnergy demand supports stability.",
 symbol: "RELIANCE",
 created_at: "2025-07-03T08:00:00Z",
 entry_price: 3000,
 exit_price: 2900,
 target_duration: "6 months",
 allocation: "10%",
 catalyst: "Oil price recovery",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "50DMA support",
 confidence: "High",
 diversification: "Reduces sector risk",
 liquidity: "High",
 expected_return: "7%",
 performance: "Last 3 tips: +5%, +3%, +6%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },

 {
 id: 24,
 name: "Xander",
 avatar: "https://randomuser.me/api/portraits/men/24.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Sun Pharma has strong R&D pipeline.\nNew drugs drive stock growth.",
 symbol: "SUNPHARMA",
 created_at: "2025-07-02T09:00:00Z",
 entry_price: 1500,
 exit_price: 1450,
 target_duration: "3 months",
 allocation: "8%",
 catalyst: "Drug approvals",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "RSI below 45, oversold",
 confidence: "High",
 diversification: "Complements healthcare portfolio",
 liquidity: "High",
 expected_return: "9%",
 performance: "Last 3 tips: +7%, +5%, +8%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Growth"
 },
 {
 id: 74,
 name: "Michael",
 avatar: "https://randomuser.me/api/portraits/men/74.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Infosys remains solid.\nMarket expects steady growth.",
 symbol: "INFY",
 created_at: "2025-05-07T10:00:00Z",
 entry_price: 1800,
 exit_price: 1850,
 target_duration: "1 month",
 allocation: "6%",
 catalyst: "Stable economy",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "Moderate",
 diversification: "Core financial holding",
 liquidity: "High",
 expected_return: "7%",
 performance: "Last 3 tips: +4%, +5%, +6%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Value"
 },
 {
 id: 75,
 name: "Nina",
 avatar: "https://randomuser.me/api/portraits/women/75.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Wipro shows steady growth.\nStrong fundamentals support gains.",
 symbol: "WIPRO",
 created_at: "2025-05-08T11:00:00Z",
 entry_price: 500,
 exit_price: 480,
 target_duration: "1 month",
 allocation: "7%",
 catalyst: "Financial reports",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "RSI at 50",
 confidence: "Moderate",
 diversification: "Balances financial exposure",
 liquidity: "High",
 expected_return: "5%",
 performance: "Last 3 tips: +3%, +2%, +1%",
 holding: "Hold",
 risk: "Low",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Value"
 },
 {
 id: 76,
 name: "Oliver",
 avatar: "https://randomuser.me/api/portraits/men/76.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "ONGC remains a core pick.\nDemand supports growth.",
 symbol: "ONGC",
 created_at: "2025-05-09T12:00:00Z",
 entry_price: 250,
 exit_price: 260,
 target_duration: "2 months",
 allocation: "5%",
 catalyst: "Sector demand",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "High",
 diversification: "Enhances portfolio",
 liquidity: "High",
 expected_return: "8%",
 performance: "Last 3 tips: +7%, +6%, +8%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Growth"
 },
 {
 id: 77,
 name: "Pamela",
 avatar: "https://randomuser.me/api/portraits/women/77.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "BPCL stock is stable.\nDefensive play amid volatility.",
 symbol: "BPCL",
 created_at: "2025-05-10T13:00:00Z",
 entry_price: 600,
 exit_price: 580,
 target_duration: "1 month",
 allocation: "6%",
 catalyst: "Sector news",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "50DMA support",
 confidence: "Moderate",
 diversification: "Defensive sector exposure",
 liquidity: "High",
 expected_return: "5%",
 performance: "Last 3 tips: +4%, +3%, +2%",
 holding: "Hold",
 risk: "Low",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Income"
 },
 {
 id: 78,
 name: "Quinn",
 avatar: "https://randomuser.me/api/portraits/women/78.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Cipla stock has upside potential.\nStrong demand in segment.",
 symbol: "CIPLA",
 created_at: "2025-05-11T14:00:00Z",
 entry_price: 1200,
 exit_price: 1250,
 target_duration: "2 months",
 allocation: "7%",
 catalyst: "Services demand",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "High",
 diversification: "Balances exposure",
 liquidity: "High",
 expected_return: "10%",
 performance: "Last 3 tips: +8%, +7%, +6%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Growth"
 },
 {
 id: 79,
 name: "Rebecca",
 avatar: "https://randomuser.me/api/portraits/women/79.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Dr Reddy's is stable.\nHealthcare demand drives returns.",
 symbol: "DRREDDY",
 created_at: "2025-05-12T15:00:00Z",
 entry_price: 5500,
 exit_price: 5400,
 target_duration: "3 months",
 allocation: "8%",
 catalyst: "Healthcare news",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "50DMA support",
 confidence: "High",
 diversification: "Defensive stock",
 liquidity: "High",
 expected_return: "6%",
 performance: "Last 3 tips: +5%, +4%, +6%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },

 // Modified Mutual Funds to Indian Stocks (Equity)

 {
 id: 25,
 name: "Yara",
 avatar: "https://randomuser.me/api/portraits/women/25.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "SBI is a long-term pick.\nFinancials show consistent growth.",
 symbol: "SBIN",
 created_at: "2025-07-01T10:00:00Z",
 entry_price: 800,
 exit_price: 780,
 target_duration: "1 year",
 allocation: "15%",
 catalyst: "Financial sector recovery",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "Price uptrend",
 confidence: "High",
 diversification: "Core portfolio holding",
 liquidity: "Medium",
 expected_return: "10%",
 performance: "Last 3 tips: +8%, +6%, +9%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Long-Term Growth"
 },

 {
 id: 26,
 name: "Zane",
 avatar: "https://randomuser.me/api/portraits/men/26.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "TCS outperforms in 2024.\nInnovation drives performance.",
 symbol: "TCS",
 created_at: "2025-06-30T11:00:00Z",
 entry_price: 4200,
 exit_price: 4100,
 target_duration: "6 months",
 allocation: "12%",
 catalyst: "Tech sector growth",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "RSI above 60",
 confidence: "Moderate",
 diversification: "Balances tech exposure",
 liquidity: "Medium",
 expected_return: "8%",
 performance: "Last 3 tips: +7%, +5%, +8%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Growth"
 },

 {
 id: 27,
 name: "Ava",
 avatar: "https://randomuser.me/api/portraits/women/27.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "Reliance is defensive in downturns.\nStable cash flows ensure returns.",
 symbol: "RELIANCE",
 created_at: "2025-06-29T12:00:00Z",
 entry_price: 3000,
 exit_price: 2900,
 target_duration: "1 year",
 allocation: "10%",
 catalyst: "Oil price stability",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Price stable",
 confidence: "High",
 diversification: "Reduces energy risk",
 liquidity: "Medium",
 expected_return: "6%",
 performance: "Last 3 tips: +5%, +4%, +6%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },

 {
 id: 28,
 name: "Ben",
 avatar: "https://randomuser.me/api/portraits/men/28.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Sun Pharma offers stability.\nStrong R&D supports growth.",
 symbol: "SUNPHARMA",
 created_at: "2025-06-28T13:00:00Z",
 entry_price: 1500,
 exit_price: 1450,
 target_duration: "1 year",
 allocation: "8%",
 catalyst: "Healthcare innovations",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "Price uptrend",
 confidence: "High",
 diversification: "Balances healthcare portfolio",
 liquidity: "Medium",
 expected_return: "7%",
 performance: "Last 3 tips: +6%, +5%, +7%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Long-Term Growth"
 },
 {
 id: 82,
 name: "Zoey",
 avatar: "https://randomuser.me/api/portraits/women/82.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Infosys outperforms IT stocks.\nLong-term innovation drives up.",
 symbol: "INFY",
 created_at: "2025-06-27T14:00:00Z",
 entry_price: 1800,
 exit_price: 1750,
 target_duration: "6 months",
 allocation: "12%",
 catalyst: "Tech growth",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "Price uptrend",
 confidence: "Moderate",
 diversification: "Balances tech exposure",
 liquidity: "Medium",
 expected_return: "8%",
 performance: "Last 3 tips: +6%, +5%, +7%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Growth"
 },
 {
 id: 83,
 name: "Andrew",
 avatar: "https://randomuser.me/api/portraits/men/83.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Wipro remains strong.\nInnovation fuels performance.",
 symbol: "WIPRO",
 created_at: "2025-06-26T15:00:00Z",
 entry_price: 500,
 exit_price: 480,
 target_duration: "6 months",
 allocation: "10%",
 catalyst: "Tech sector growth",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "Price uptrend",
 confidence: "High",
 diversification: "Balances tech exposure",
 liquidity: "Medium",
 expected_return: "9%",
 performance: "Last 3 tips: +7%, +6%, +8%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Long-Term Growth"
 },
 {
 id: 84,
 name: "Beth",
 avatar: "https://randomuser.me/api/portraits/women/84.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "ONGC offers good returns.\nStable returns in volatile markets.",
 symbol: "ONGC",
 created_at: "2025-06-25T16:00:00Z",
 entry_price: 250,
 exit_price: 240,
 target_duration: "1 year",
 allocation: "9%",
 catalyst: "Oil price stabilization",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Price stable",
 confidence: "High",
 diversification: "Reduces energy risk",
 liquidity: "Medium",
 expected_return: "6%",
 performance: "Last 3 tips: +4%, +3%, +5%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },
 {
 id: 85,
 name: "Carl",
 avatar: "https://randomuser.me/api/portraits/men/85.jpg",
 asset_type: "Equity",
 sector: "Energy",
 tip: "BPCL is steady.\nDiversifies energy exposure.",
 symbol: "BPCL",
 created_at: "2025-06-24T17:00:00Z",
 entry_price: 600,
 exit_price: 580,
 target_duration: "1 year",
 allocation: "8%",
 catalyst: "Energy demand",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Price uptrend",
 confidence: "Moderate",
 diversification: "Balances energy exposure",
 liquidity: "Medium",
 expected_return: "5%",
 performance: "Last 3 tips: +3%, +2%, +4%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },
 {
 id: 86,
 name: "Diana",
 avatar: "https://randomuser.me/api/portraits/women/86.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Cipla is safe.\nStability in healthcare sector.",
 symbol: "CIPLA",
 created_at: "2025-06-23T18:00:00Z",
 entry_price: 1200,
 exit_price: 1200,
 target_duration: "1 year",
 allocation: "10%",
 catalyst: "Stable policy rates",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Price stable",
 confidence: "High",
 diversification: "Reduces volatility",
 liquidity: "Medium",
 expected_return: "3%",
 performance: "Last 3 tips: +1%, +1%, +1%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "90%",
 strategy: "Income"
 },
 {
 id: 87,
 name: "Ethan",
 avatar: "https://randomuser.me/api/portraits/men/87.jpg",
 asset_type: "Equity",
 sector: "Financials",
 tip: "ICICI Bank delivers stable returns.\nConsistent performance in finance sector.",
 symbol: "ICICIBANK",
 created_at: "2025-06-22T19:00:00Z",
 entry_price: 1100,
 exit_price: 1050,
 target_duration: "1 year",
 allocation: "8%",
 catalyst: "Bank earnings",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "Price uptrend",
 confidence: "High",
 diversification: "Balances financial exposure",
 liquidity: "Medium",
 expected_return: "7%",
 performance: "Last 3 tips: +5%, +4%, +6%",
 holding: "Buy",
 risk: "Low",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Growth"
 },
 {
 id: 88,
 name: "Fiona",
 avatar: "https://randomuser.me/api/portraits/women/88.jpg",
 asset_type: "Equity",
 sector: "Healthcare",
 tip: "Dr Reddy's is a defensive pick.\nStable returns from pharma sector.",
 symbol: "DRREDDY",
 created_at: "2025-06-21T20:00:00Z",
 entry_price: 5500,
 exit_price: 5400,
 target_duration: "6 months",
 allocation: "10%",
 catalyst: "Healthcare pipeline",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Price stable",
 confidence: "Moderate",
 diversification: "Balances healthcare exposure",
 liquidity: "Medium",
 expected_return: "6%",
 performance: "Last 3 tips: +4%, +3%, +5%",
 holding: "Hold",
 risk: "Low",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Income"
 },
 {
 id: 89,
 name: "Grace",
 avatar: "https://randomuser.me/api/portraits/women/89.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "HCL Tech captures growth.\nInnovation drives upward.",
 symbol: "HCLTECH",
 created_at: "2025-06-20T21:00:00Z",
 entry_price: 1400,
 exit_price: 1350,
 target_duration: "6 months",
 allocation: "9%",
 catalyst: "Tech earnings",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "Price uptrend",
 confidence: "High",
 diversification: "Balances tech exposure",
 liquidity: "Medium",
 expected_return: "7%",
 performance: "Last 3 tips: +6%, +5%, +7%",
 holding: "Buy",
 risk: "Medium",
 conviction: "Strong",
 win_rate: "85%",
 strategy: "Growth"
 },

 // Modified Crypto to Indian Stocks (Equity)

 {
 id: 29,
 name: "Cara",
 avatar: "https://randomuser.me/api/portraits/women/29.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "TCS remains the top IT asset.\nAdoption drives long-term value.",
 symbol: "TCS",
 created_at: "2025-06-27T14:00:00Z",
 entry_price: 4200,
 exit_price: 4100,
 target_duration: "1 month",
 allocation: "5%",
 catalyst: "Institutional adoption",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "RSI above 65",
 confidence: "Moderate",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +10%, +8%, +12%",
 holding: "Buy",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Speculative"
 },
 {
 id: 90,
 name: "Cara",
 avatar: "https://randomuser.me/api/portraits/women/90.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Infosys drives long-term value.\nAdoption trends boost outlook.",
 symbol: "INFY",
 created_at: "2025-06-07T00:00:00Z",
 entry_price: 1800,
 exit_price: 1700,
 target_duration: "2 weeks",
 allocation: "4%",
 catalyst: "Sector growth",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "MACD bullish crossover",
 confidence: "High",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "12%",
 performance: "Last 3 tips: +10%, +8%, +9%",
 holding: "Buy",
 risk: "High",
 conviction: "Medium",
 win_rate: "75%",
 strategy: "Speculative"
 },
 {
 id: 91,
 name: "Danny",
 avatar: "https://randomuser.me/api/portraits/men/91.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Wipro offers diversification.\nVolatility remains high but potential persists.",
 symbol: "WIPRO",
 created_at: "2025-06-06T01:00:00Z",
 entry_price: 500,
 exit_price: 480,
 target_duration: "1 week",
 allocation: "3%",
 catalyst: "Market sentiment",
 valuation: "Overvalued",
 sentiment: "Neutral",
 technical: "RSI at 50",
 confidence: "Moderate",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "10%",
 performance: "Last 3 tips: +8%, +6%, +7%",
 holding: "Hold",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Speculative"
 },
 {
 id: 92,
 name: "Elena",
 avatar: "https://randomuser.me/api/portraits/women/92.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "HCL Tech sees growth.\nAdoption may drive movement.",
 symbol: "HCLTECH",
 created_at: "2025-06-05T02:00:00Z",
 entry_price: 1400,
 exit_price: 1450,
 target_duration: "2 weeks",
 allocation: "3%",
 catalyst: "Sector adoption",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "MACD bullish signal",
 confidence: "High",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +12%, +10%, +8%",
 holding: "Buy",
 risk: "High",
 conviction: "Strong",
 win_rate: "78%",
 strategy: "Growth"
 },
 {
 id: 93,
 name: "Frankie",
 avatar: "https://randomuser.me/api/portraits/men/93.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Tech Mahindra remains speculative.\nMarket sentiment drives price.",
 symbol: "TECHM",
 created_at: "2025-06-04T03:00:00Z",
 entry_price: 1400,
 exit_price: 1450,
 target_duration: "1 month",
 allocation: "2%",
 catalyst: "Market buzz",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "RSI below 40, oversold",
 confidence: "Moderate",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +14%, +10%, +12%",
 holding: "Buy",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Speculative"
 },
 {
 id: 94,
 name: "George",
 avatar: "https://randomuser.me/api/portraits/men/94.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Infosys focuses on growth.\nLong-term fundamentals are promising.",
 symbol: "INFY",
 created_at: "2025-06-03T04:00:00Z",
 entry_price: 1800,
 exit_price: 1750,
 target_duration: "2 weeks",
 allocation: "3%",
 catalyst: "Upgrades",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "MACD neutral",
 confidence: "Moderate",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +12%, +10%, +13%",
 holding: "Hold",
 risk: "High",
 conviction: "Medium",
 win_rate: "72%",
 strategy: "Growth"
 },
 {
 id: 95,
 name: "Hannah",
 avatar: "https://randomuser.me/api/portraits/women/95.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "TCS shows growth.\nUsage drives value.",
 symbol: "TCS",
 created_at: "2025-06-02T05:00:00Z",
 entry_price: 4200,
 exit_price: 4300,
 target_duration: "3 weeks",
 allocation: "3%",
 catalyst: "Adoption",
 valuation: "Undervalued",
 sentiment: "Bullish",
 technical: "RSI above 65",
 confidence: "High",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +12%, +10%, +14%",
 holding: "Buy",
 risk: "High",
 conviction: "Strong",
 win_rate: "75%",
 strategy: "Growth"
 },
 {
 id: 96,
 name: "Isaac",
 avatar: "https://randomuser.me/api/portraits/men/96.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Wipro connects sectors.\nActivity supports long-term value.",
 symbol: "WIPRO",
 created_at: "2025-06-01T06:00:00Z",
 entry_price: 500,
 exit_price: 520,
 target_duration: "3 weeks",
 allocation: "3%",
 catalyst: "Upgrades",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "MACD neutral",
 confidence: "Moderate",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "14%",
 performance: "Last 3 tips: +12%, +9%, +11%",
 holding: "Hold",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Growth"
 },
 {
 id: 97,
 name: "Julia",
 avatar: "https://randomuser.me/api/portraits/women/97.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "HCL Tech drives sector.\nDemand fuels growth.",
 symbol: "HCLTECH",
 created_at: "2025-05-31T07:00:00Z",
 entry_price: 1400,
 exit_price: 1450,
 target_duration: "2 weeks",
 allocation: "3%",
 catalyst: "Adoption",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "RSI above 60",
 confidence: "High",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +14%, +12%, +13%",
 holding: "Buy",
 risk: "High",
 conviction: "Strong",
 win_rate: "78%",
 strategy: "Growth"
 },
 {
 id: 98,
 name: "Kyle",
 avatar: "https://randomuser.me/api/portraits/men/98.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Tech Mahindra is a solution.\nAdoption trends will drive value.",
 symbol: "TECHM",
 created_at: "2025-05-30T08:00:00Z",
 entry_price: 1400,
 exit_price: 1350,
 target_duration: "3 weeks",
 allocation: "2%",
 catalyst: "Demand",
 valuation: "Fair",
 sentiment: "Neutral",
 technical: "Bollinger Bands neutral",
 confidence: "Moderate",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +13%, +12%, +14%",
 holding: "Hold",
 risk: "High",
 conviction: "Medium",
 win_rate: "70%",
 strategy: "Growth"
 },
 {
 id: 99,
 name: "Laura",
 avatar: "https://randomuser.me/api/portraits/women/99.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Infosys fuels sector.\nDemand supports growth.",
 symbol: "INFY",
 created_at: "2025-05-29T09:00:00Z",
 entry_price: 1800,
 exit_price: 1900,
 target_duration: "2 weeks",
 allocation: "3%",
 catalyst: "Usage",
 valuation: "Overvalued",
 sentiment: "Bullish",
 technical: "RSI above 70",
 confidence: "High",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "16%",
 performance: "Last 3 tips: +15%, +13%, +14%",
 holding: "Buy",
 risk: "High",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Growth"
 },
 {
 id: 100,
 name: "Michael",
 avatar: "https://randomuser.me/api/portraits/men/100.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "TCS is fast and scalable.\nDemand drives value.",
 symbol: "TCS",
 created_at: "2025-05-28T10:00:00Z",
 entry_price: 4200,
 exit_price: 4300,
 target_duration: "2 weeks",
 allocation: "2%",
 catalyst: "Sector demand",
 valuation: "Fair",
 sentiment: "Bullish",
 technical: "MACD bullish signal",
 confidence: "High",
 diversification: "High-risk tech exposure",
 liquidity: "High",
 expected_return: "15%",
 performance: "Last 3 tips: +14%, +13%, +12%",
 holding: "Buy",
 risk: "High",
 conviction: "Strong",
 win_rate: "80%",
 strategy: "Growth"
 },
 {
 id: 101,
 name: "Alice",
 avatar: "https://randomuser.me/api/portraits/women/101.jpg",
 asset_type: "Equity",
 sector: "Technology",
 tip: "Wipro sees volatility on event.\nAdoption trends drive long-term value.",
 symbol: "WIPRO",
 created_at: "2025-04-16T14:00:00Z",
 entry_price: 500,
 exit_price: 480,
 target_duration: "3 days",
 allocation: "15%",
 catalyst: "Geopolitical event",
 valuation: "Undervalued",
 sentiment: "Neutral",
 technical: "RSI above 61",
 confidence: "Moderate",
 diversification: "Balances sector risk",
 liquidity: "Very High",
 expected_return: "15%",
 performance: "Last 3 tips: +7%, -5%, +9%",
 holding: "Hold",
 risk: "Low",
 conviction: "Weak",
 win_rate: "67%",
 strategy: "Dividend"
 }
];

export function timeAgo(dateString: string) {
  const now = new Date();
  const date = new Date(dateString);
  const diff = Math.floor((now.getTime() - date.getTime()) / 1000);
  if (diff >= 0) {
    if (diff < 60) return `${diff}s ago`;
    if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
    if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
    return `${Math.floor(diff / 86400)}d ago`;
  } else {
    // Future date
    const futureDiff = Math.abs(diff);
    if (futureDiff < 60) return `${futureDiff}s ago`;
    if (futureDiff < 3600) return `${Math.floor(futureDiff / 60)}m ago`;
    if (futureDiff < 86400) return `${Math.floor(futureDiff / 3600)}h ago`;
    return `${Math.floor(futureDiff / 86400)}d ago`;
  }
}